export const LOCALITIES_BY_CITY = {
  "Bangalore": [
    "1A Block Koramangala",
    "1st Block East",
    "A Narayanapura",
    "Abbaiah Reddy Layout",
    "Abbigere",
    "Adarsh Palm Retreat",
    "Aditya nagar",
    "Adugodi",
    "AECS Layout Block A",
    "AECS Layout Block D",
    "AECS Layout-Singasandra",
    "Agrahara Layout",
    "AK Colony Domlur",
    "Akshya Nagar",
    "Amarjyoti Layout-Domlur",
    "Ambalipura",
    "Ambalipura Sarjapur Road",
    "Amrutahalli",
    "Amruthnagar",
    "AMS Layout",
    "Anand Nagar- Hebbal",
    "Anantapura",
    "Anchepalya",
    "Andrahalli",
    "Anjana Nagar",
    "Anjanadri Layout",
    "AnjanaPura",
    "Anjanapura Township",
    "Annapurneshwari Nagar",
    "Annasandrapalya Extension",
    "Arekere",
    "Ashok Nagar",
    "Ashwini layout",
    "Atmananda Colony",
    "Attibele",
    "Attibele Anekal Road",
    "Attur Layout",
    "Avalahalli",
    "Ayappa Nagar KR Puram",
    "B Narayanapura",
    "Babusahib Palya",
    "Bagalur Main Road",
    "Bagalur Sarjapur Road",
    "Bagaluru",
    "Balagere",
    "Balaji Layout",
    "Balaji Layout Cooke Town",
    "Banashankari",
    "Banashankari 6th Stage-11th Block",
    "Banashankari Stage 1",
    "Banashankari Stage 2",
    "Banashankari Stage 3",
    "Banashankari stage 6",
    "Banaswadi",
    "Bangalore Shivamogga Road",
    "Bank Colony Konanakunte",
    "Bannerghatta",
    "Bannerghatta Road",
    "Bapuji Nagar",
    "Basapura",
    "Basapura Main Road",
    "Basavanagar Main Road",
    "Basavanagara",
    "Basavanagudi",
    "Basavanapura",
    "Basavanna Nagar",
    "Basaveshwar Nagar",
    "Basaveshwara HBCS Layout",
    "Battarahalli",
    "BCC Layout",
    "BDA Lay Out Chandra Layout",
    "BDA layout-HSR Layout",
    "Begur",
    "Begur Hulimavu Road",
    "Begur Road",
    "Bellandur",
    "Bellandur Lake Road",
    "Bellandur-Marathahalli",
    "Bellary Road",
    "BEML Layout-Brookefield",
    "Bengaluru Kanakapura Road",
    "Bengaluru Main Road",
    "Benson Town",
    "Bettadasanapura",
    "Bhavani Nagar",
    "Bhavani Nagar Shakti Farm",
    "Bhoganhalli",
    "Bhuvaneshwari Nagar",
    "Bhyraveshwara Nagar",
    "Bidarahalli",
    "Bidare Agrahara",
    "Bikasipura",
    "Bilekahalli",
    "Bileshivale",
    "Binnamangala Stage 1 Indiranagar",
    "Binny Pete",
    "Block 1st JayaNagar",
    "Block 1st Koramangala",
    "Block 2nd JayaNagar East",
    "Block 2nd Koramangala",
    "Block 3rd Jayanagar East",
    "Block 3rd Koramangala",
    "Block 3rd Narayana Nagar",
    "Block 4th Jayanagar",
    "Block 5th Jayanagar",
    "Block 5th Koramangala",
    "Block 6th Koramangala",
    "Block 7th Jayanagar",
    "Bommanahalli",
    "Bommasandra",
    "Bommasandra Jigani Link Road",
    "Borewell Road",
    "Brigade Metropolis",
    "Brindavan Nagar Mathikere",
    "Brookefield",
    "BTM Layout",
    "BTM Layout Stage 1",
    "BTM Layout Stage 2",
    "Budigere",
    "Budigere Road",
    "Byatarayanapura New Extension",
    "Byrappa Layout RMV 2nd Stage",
    "Byrathi",
    "C V Raman Nagar",
    "Cambridge Layout",
    "Canara bank Layout",
    "Chamrajpet",
    "Chamundeshwari Layout",
    "Chandapura",
    "Channasandra",
    "Channasandra Main Road",
    "Chennammana Kere",
    "Chikkabanavara",
    "Chikkabellandur",
    "Chikkabidarakallu",
    "Chikkagubbi Village",
    "Chikkajala",
    "Chikkakannalli",
    "Chikkalasandra",
    "Chikkanna Layout",
    "Chikku Lakshmaiah Layout",
    "Chinnapanna Halli",
    "Chokkanahalli",
    "Choodasandra",
    "Chowdeshwari Layout Marathahalli Village",
    "Chunchanakuppe",
    "Cleveland Town",
    "Coffee Board layout",
    "Cooke Town",
    "Cox Town",
    "CQAL Layout",
    "Cunningham Road",
    "D Group Layout",
    "Dasarahalli",
    "Dasarahalli Main Road",
    "Deepanjali Nagar",
    "Defence Enclave",
    "Devanahalli",
    "Devappa Layout",
    "Devarabisanahalli",
    "Devarachikkana Halli",
    "Devasthanagalu",
    "Devinagar",
    "Doddaballapur Main Road",
    "Doddakallasandra",
    "Doddakannelli",
    "Doddanagamangala",
    "Doddanekundi",
    "Doddanekundi Main Road",
    "Doddathoguru",
    "Dollar Scheme",
    "Dollars Colony",
    "Domlur",
    "Doopanahalli",
    "Dooravani Nagar",
    "ECC Road",
    "Ejipura",
    "Electronic City",
    "Electronic City Phase 2",
    "Electronics City Phase 1",
    "Elus Road",
    "EPIP Zone",
    "Ex Service Men Colony",
    "F Block Sahakar Nagar",
    "Frazer Town",
    "G Block Sahakar Nagar",
    "Gandhi Bazar",
    "Ganga Nagar Layout",
    "Ganganagar",
    "Gattahalli",
    "GM Palya",
    "Gollarahatti",
    "Gopasandra Sarjapura Road",
    "Gottigere",
    "Govindpura",
    "Green Woods layout",
    "Gruha Lakshmi Layout",
    "Gubbalala",
    "Gummanahalli",
    "Gunjur",
    "Gunjur Balagere Road",
    "Hadosiddapura",
    "HAL 3rd Stage",
    "HAL Old Airport Road",
    "Halanayakanahalli",
    "Halasuru",
    "Hanumanthappa Layout Sivanchetti Gardens",
    "Haralur",
    "Haralur Main Road",
    "Harlur",
    "Harsha Layout",
    "HBR Layout",
    "HBR Layout Block 2",
    "HBR Layout Block 3",
    "Hebbal",
    "Hebbal Kempapura",
    "Hegde Nagar",
    "Hennur",
    "Hennur Bagalur Main Road",
    "Hennur Bande Road",
    "Hennur Main Road",
    "Hesarghatta Road",
    "HMT Layout Vidyaranyapura",
    "Holiday Village Road",
    "Hongasandra",
    "Hoodi",
    "Horamavu",
    "Horamavu Main Road",
    "Hosa Road",
    "Hosakerehalli",
    "Hoskote",
    "Hoskote Road",
    "Hosur Road",
    "Hoysalanagar",
    "HRBR Layout",
    "HRBR Layout Block 1",
    "HSR Layout",
    "Hulimavu",
    "Hunasamaranahalli",
    "Huskur",
    "Hutchins Road",
    "Huvinayakanahalli",
    "Iblur Village",
    "Immadihalli",
    "Indira Nagar",
    "Indira nagar Stage 1",
    "Indira nagar Stage 2",
    "Infantry Road",
    "ISRO Layout",
    "ITI Layout",
    "ITPL",
    "ITPL Main Road",
    "Ittamadu Main Road",
    "IVC Road",
    "Jakkasandra Extension",
    "Jakkur",
    "jakkur Plantation",
    "Jakkuru Main Road",
    "Jalahalli",
    "Jalahalli East",
    "Jalahalli West",
    "Jayamahal Main Road",
    "Jayanagar",
    "Jayanagar Housing Society Layout",
    "JC Nagar-Kurubarahalli",
    "Jeevan Bima Nagar",
    "Jigani",
    "Jivanahalli",
    "JP Nagar",
    "Judicial Layout",
    "Junnasandra",
    "K Channasandra",
    "Kada Agrahara",
    "Kadabagere",
    "Kadubeesanahalli",
    "Kadugodi",
    "Kadugondanahalli",
    "Kaggadasapura",
    "Kaikondrahalli",
    "Kalappa Layout",
    "Kalena Agrahara",
    "Kalidasa Layout",
    "Kalyan Nagar",
    "Kamakshipalya",
    "Kammagondahalli",
    "Kammanahalli",
    "Kammasandra",
    "Kanaka Nagar",
    "Kanakapura",
    "Kanakapura Road",
    "Kannamangala",
    "Kannuru",
    "Kariobanahalli",
    "Kariyammana Agrahara",
    "Karthik Nagar",
    "Kasavanahalli",
    "Kasturi Nagar",
    "Kattigenahalli",
    "Kaval Byrasandra",
    "Kaveri Nagar",
    "Kempapura",
    "Kempapura Agrahara",
    "Kenchenhalli",
    "Kengeri",
    "Kengeri Main Road",
    "Kengeri Satellite Town",
    "Kithaganur Main Road",
    "Kodathi",
    "Kodichikknahalli",
    "Kodigehalli",
    "Kodigenahalli",
    "Kodihalli",
    "Kodipalya",
    "Kogilu",
    "Kogilu Main Road",
    "Konanakunte",
    "Konena Agrahara Murgesh Pallya",
    "Koppa",
    "Koramangala",
    "Koramangala 80 Feet Road",
    "Koramangala Block 4",
    "Kothnoor Dinne",
    "Kothnur",
    "KR Puram",
    "Kudlu",
    "Kudlu Gate",
    "Kumara park West",
    "Kumaraswamy Layout",
    "Kumbalgodu",
    "Kundalahalli",
    "Kundalahalli Colony",
    "Laggere",
    "Lakkasandra Extension",
    "Lakshminarayana Pura",
    "Lakshmipura",
    "Lavakusha Nagar",
    "Lavelle Road",
    "Laxmi Sagar Layout",
    "LBS Nagar",
    "Lingarajapuram",
    "Madavara",
    "Madhuranagara",
    "Mahadevapura",
    "Mahadevapura Layout",
    "Mahalakshmipuram Layout",
    "Mahatma Gandhi Nagar",
    "Mahatma Gandhi Road",
    "Maithri Layout",
    "Mallasandra Village",
    "Mallathahalli",
    "Malleshpalya",
    "Malleshpalya Main Road",
    "Malleshwaram",
    "Mangammanapalya",
    "ManganaHalli",
    "Manjunatha Layout Munnekollal",
    "Manjunatha Nagar Kalkere",
    "Manorayana Palya",
    "Manyata Residency",
    "Manyata Tech Park",
    "Manyata Tech Park Road",
    "Marathahalli",
    "Marathahalli Sarjapur Outer Ring Road",
    "Marathahalli village",
    "Marenahalli - Vijaynagar",
    "Margondanahalli",
    "Maruthi Nagar Attiguppe",
    "Maruthi Nagar Dasarahalli",
    "Maruthi Nagar Yelahanka",
    "Maruti Nagar",
    "Matadahalli",
    "Mathikere",
    "Mathikere Extension",
    "Mathrushree Layout Doddamuniswamy Reddy Layout",
    "Mavalli",
    "MC Layout",
    "MCECHS Layout",
    "MedaHalli",
    "Medi Agrahara",
    "Meenakshi Layout Choodasandra",
    "Michael Palya",
    "Mico Layout",
    "Mitganahalli",
    "MKS Layout",
    "Moodalapalya",
    "MS Palya",
    "MS Ramaiah City Layout",
    "Mullur",
    "Munikalappa Layout",
    "Munireddy Layout",
    "Munnekollal",
    "Murugeshpalya",
    "Muthanallur",
    "Mylappanahalli",
    "Mysore Road",
    "Naganathapura",
    "Nagapura",
    "Nagarbhavi",
    "Nagasandra",
    "Nagasandra Main Road",
    "Nagavara",
    "Nagdevanahalli",
    "Nagegowdanapalya",
    "Nagondanahalli",
    "Naidu Layout Electronic City",
    "Nallurhalli",
    "Nandi Hills",
    "Nandini Layout",
    "Nanjappa Layout Adugodi",
    "Narayanaghatta",
    "Nayandahalli",
    "Neeladri Nagar",
    "Neelasandra",
    "Nehru Nagar",
    "NelaMangala",
    "New International Airport Road",
    "Nisarga Nandana Layout",
    "NR Colony",
    "Nyanapanahalli",
    "Old Guddadahalli",
    "Old Madras Road",
    "OMBR Layout",
    "Pai Layout Hulimavu",
    "Pai Layout Mahadevapura",
    "Palace Cross Road",
    "Palanahalli Road",
    "Panathur",
    "Papareddipalya",
    "Parappana Agrahara",
    "Patteghar Palya Main Road",
    "Peace layout",
    "Phase 1 Sivagiri Township",
    "Phase 1st JP Nagar",
    "Phase 1st MCECHS Layout",
    "Phase 2nd JP Nagar",
    "Phase 3 Reliable Residency Layout",
    "Phase 5 JP Nagar",
    "Phase 7 JP Nagar",
    "Phase 8th JP Nagar",
    "Pillaganahalli",
    "PNS Layout",
    "Pragathi Nagar",
    "Prithvi layout",
    "Pulkeshi Nagar",
    "Puttanahalli",
    "Rachenahalli",
    "Rachenahalli Main Road",
    "Raghuvanahalli BCMC Layout",
    "Rainbow Drive",
    "Rajaji Nagar",
    "Rajaji Nagar Block 1",
    "Rajaji Nagar Block 2",
    "Rajaji Nagar Industrial Town",
    "Rajajinagar Stage 2",
    "Rajanukunte",
    "Rajarajeshwari Nagar",
    "Rajarajeshwari Nagar Stage 5",
    "Ramagondanahalli-Whitefield",
    "Ramamurthy Nagar",
    "Ramanjaneyanagar",
    "Ramchandrapura",
    "Rayasandra",
    "Rayasandra Main Road",
    "RBI Layout",
    "RHCS Layout",
    "Richards Town",
    "Richmond Road",
    "Richmond Town",
    "Ring Road",
    "RMV Extension",
    "RMV Extension Stage 2",
    "Royal Shelters",
    "RPC Layout",
    "RS Palya",
    "RT Nagar",
    "Rustam Bagh Layout",
    "Sadahalli Main Road",
    "Sadashiva Nagar",
    "Sahakara Nagar",
    "Samethanahalli",
    "Sampigehalli",
    "Sanjayanagara",
    "Sannatammanahalli",
    "Sarjapur",
    "Sarjapur Road",
    "Sarjapura Attibele Road",
    "Sathanur",
    "Sathya Sai Layout",
    "Sector 1 HSR Layout",
    "Sector 11 New Thippasandra",
    "Sector 2 HSR Layout",
    "Sector 3 HSR Layout",
    "Sector 4 HSR Layout",
    "Sector 5 HSR Layout",
    "Sector 6 HSR Layout",
    "Seegehalli",
    "Seegehalli Kannamangala Road",
    "Seegehalli KR Puram",
    "Seegehalli Road",
    "SG Palya",
    "Shanthala Nagar",
    "Shanti Nagar",
    "Siddapur",
    "Silicon Town",
    "Silver County Road",
    "Silver Oak Layout",
    "Sindhi Colony",
    "Singapura",
    "Singasandra",
    "Sir M Visvesvaraya Inst Road",
    "Soladevanahalli",
    "Somasundarapalya",
    "Someshwara Layout",
    "Sompura",
    "Spencer Road",
    "Spice Garden Layout",
    "Sri Balaji Layout",
    "Sri Sai Layout",
    "Srigandha Nagar",
    "Srinagar",
    "Srirampuram",
    "Stage 1st Kumaraswamy Layout",
    "State Highway 104",
    "Subbaiahnapalya",
    "Subs Nagar",
    "Sudhama Nagar",
    "Sultanpalya",
    "Sunkadakatte",
    "Suryanagar",
    "Syndicate Bank Colony",
    "T Dasarahalli",
    "Talacauvery Layout",
    "Talaghattapura",
    "Tata Nagar",
    "Tavarekere",
    "Tavarekere BTM Layout",
    "Teachers Colony -HSR Layout",
    "Tejaswini Nagar Phase 1",
    "Thambu Chetty Palya",
    "Thanisandra",
    "Thanisandra Main Road",
    "Thigalarapalya",
    "Thindlu",
    "Thirumenahalli",
    "Thubarahalli",
    "Thurahalli",
    "Thyagaraja Nagar",
    "Trinity Church Road",
    "Tulasi Layout",
    "Tumkur Road",
    "Udaya nagar",
    "Upkar Layout Whitefield",
    "Uttarahalli",
    "Uttarahalli Main Road",
    "V Kallahalli",
    "Vagdevi Layout",
    "Valepura",
    "Varanasi",
    "Varthur",
    "Varthur Kodi",
    "Vasanth Nagar",
    "Vasanth Vihar AWHO",
    "Veerannapalya",
    "Veerasandra",
    "Vibhutipura",
    "Victoria Layout",
    "Vidhana Soudha Layout",
    "Vidyaranyapura",
    "Vignan Nagar",
    "Vigneshwara Layout Hoysala Nagar",
    "Vijaya Bank Layout Bommanahalli",
    "Vijayanagar",
    "Vijayapura Town",
    "Vimanapura",
    "Vinayak Nagar",
    "Virgonagar Industrial Estate",
    "Virupakshapura",
    "Vittal Mallya Road",
    "Vittasandra Main Road",
    "Viveka Nagar",
    "Vyalikaval",
    "Vyalikaval HBCS Layout",
    "Whitefield",
    "Wilson Garden",
    "Yelachenahalli",
    "Yelahanka",
    "Yelahanka Air Force base",
    "Yelahanka New Town",
    "Yelenahalli",
    "Yellappa Chetty Layout",
    "Yemalur",
    "Yeswanthpur",
  ],
  "Mumbai": [
    "90 Feet Road",
    "Aarey Colony",
    "Abhyudaya Nagar",
    "Adarsh Nagar Jogeshwari West",
    "Agar Bazar",
    "Agripada",
    "Ajit Nagar",
    "Amar Nagar Mulund West",
    "Ambewadi Malad East",
    "Amboli",
    "Amrut Nagar Ghatkopar West",
    "Anand Nagar Dahisar East",
    "Andheri",
    "Andheri East",
    "Andheri West",
    "Ashok Nagar Kandivali East",
    "Atur Park",
    "Azad Nagar Andheri East",
    "Azad Nagar Andheri West",
    "Babhai Naka - Borivali West",
    "Bachani Nagar",
    "Bandra",
    "Bandra East",
    "Bandra Kurla Complex",
    "Bandra West",
    "Bangur Nagar",
    "Barve Nagar",
    "Battipada",
    "Best Colony Chembur East",
    "Best Colony Parel",
    "Best Nagar - Goregaon West",
    "Bhakti Park",
    "Bhandup",
    "Bhandup East",
    "Bhandup Village Road",
    "Bhandup West",
    "Bhatwadi Ghatkopar West",
    "Bhayandar East",
    "Bhayandar West",
    "Bhoiwada - Parel",
    "Bolinj",
    "Borivali",
    "Borivali East",
    "Borivali West",
    "Breach Candy",
    "Brhmanwada",
    "Byculla",
    "Central Area",
    "Central Avenue Road",
    "Central Ordanance Depot",
    "Chakala",
    "Chakala MIDC",
    "Chandan Nagar",
    "Chandivali",
    "Charkop",
    "Charni Road",
    "Chedda Nagar",
    "Chembur",
    "Chimaji Nagar",
    "Chincholi Phatak",
    "Chinchpokli",
    "Chunabhatti",
    "Churchgate",
    "Citizen Colony",
    "Colaba",
    "Cuffe Parade",
    "Dadar",
    "Dadar East",
    "Dadar West",
    "Dahanukar Wadi",
    "Dahisar",
    "Dahisar East",
    "Dahisar West",
    "Danda",
    "Dattapada",
    "Deonar",
    "Deonar Chembur",
    "Deonar Farm Road",
    "Deonar Village Road",
    "Devidas Road",
    "Devipada",
    "Dindoshi - Malad East",
    "Eden Gardens",
    "Eksar Road",
    "Ekta Nagar Kandivali West",
    "Evershine Millennium Paradise",
    "Evershine Nagar",
    "Film City Road",
    "Fish Market Area",
    "Fort",
    "Four Bungalows",
    "Gaikwad Nagar Malad West",
    "Gandhi Nagar Bandra East",
    "Gandhi Nagar Upper Worli",
    "Ganesh Nagar Kalaram Nagar",
    "Garodia Nagar",
    "Gavane Pada",
    "Gavanpada",
    "Geeta Nagar Mira Road East",
    "Ghatkopar",
    "Ghatkopar East",
    "Ghatkopar West",
    "Ghodapdeo",
    "Ghodbunder Road",
    "Gilbert Hill",
    "Girgaon",
    "Godrej Colony",
    "Gokuldham",
    "Gorai",
    "Gorai 1",
    "Gorai 2",
    "Goregaon",
    "Goregaon East",
    "Goregaon Mulund Link Road",
    "Goregaon West",
    "Govandi",
    "Govind Nagar Bhandup West",
    "Govind Nagar Borivali West",
    "Gowalia Tank",
    "Grant Road East",
    "Green Hills",
    "GTB Nagar",
    "Gulshan Nagar",
    "Hatkesh Udhog Nagar",
    "Hindu Colony",
    "IC Colony",
    "Inlaks Nagar",
    "Irani Wadi",
    "Jacob Circle",
    "Jankalyan Nagar",
    "Janki Kutir",
    "Jawahar Nagar",
    "Jayprakash Nagar",
    "JB Nagar",
    "Jijamata Road",
    "Jogeshwari East",
    "Jogeshwari Vikhroli Link Road",
    "Jogeshwari West",
    "Juhu",
    "Juhu Scheme",
    "Juhu Versova Link Road",
    "JVPD Scheme",
    "Kala Nagar",
    "Kalachauki",
    "Kalachowki",
    "Kalbadevi",
    "Kalina",
    "Kamgar Nagar Prabhadevi",
    "Kanakiya",
    "Kanchpada",
    "Kandivali",
    "Kandivali East",
    "Kandivali West",
    "Kanjurmarg",
    "Kanjurmarg East",
    "Kanjurmarg West",
    "Kannamwar Nagar 1",
    "Kemps Corner",
    "Ketkipada",
    "Khar Danda",
    "Khar West",
    "Kharodi",
    "Khatau Estate",
    "Kirol Village",
    "Kokanipada",
    "Kolivery Village",
    "Kondivita Village Andheri East",
    "Korba Mithagar",
    "Kurar Village",
    "Kurla",
    "Kurla East",
    "Kurla West",
    "Lal Bahadur Shastri Nagar Dahisar West",
    "Lal Bahadur Shastri Road",
    "Lal Baug",
    "Lalbaug Sion",
    "LBS Road",
    "Liberty Garden",
    "LIC Colony Borivali West",
    "LIC Colony Vile Parle West",
    "Linking Road",
    "Lokhandwala Complex Andheri West",
    "Lokhandwala Township Kandivali East",
    "Lower Parel",
    "Madh",
    "Magathane",
    "Mahalakshmi",
    "Mahavir Nagar Kandivali West",
    "Mahim",
    "Mahim United Industrial Estate",
    "Mahim West",
    "Malabar Hill",
    "Malad East",
    "Malad West",
    "Mandvi",
    "Manish Nagar",
    "Mankhurd",
    "Marol",
    "Marve Road",
    "Masjid Bandar",
    "Masjid Bandar West",
    "Matunga",
    "Matunga East",
    "Matunga West",
    "Mazgaon",
    "MBH Colony",
    "MHADA Colony Mulund East",
    "Mindspace",
    "Mira Bhayandar",
    "Mira Road",
    "Model Town Andheri West",
    "MR Society",
    "Mulund",
    "Mulund East",
    "Mulund West",
    "Mumbai Central",
    "Mumbai CST Area",
    "Muranjan Wadi",
    "Mysore Colony",
    "Nagpada",
    "Nahar Nagar",
    "Nahur East",
    "Naidu Colony",
    "Naigaon East",
    "Naigaon East Vasai Link Road",
    "Naigaon Palghar",
    "Naigaon West",
    "Nala Sopara",
    "Nalasopara East",
    "Nalasopara West",
    "Napean Sea Road",
    "Navagaon",
    "Navghar Mulund East",
    "Neelam Nagar",
    "Nehru Nagar Airport Area",
    "Nerul",
    "New Golden Nest Road",
    "Nityanand Nagar Ghatkopar West",
    "Old Ferry Road",
    "Orlem",
    "Oshiwara",
    "Padmavati Nagar Bhayandar West",
    "Pali Hill",
    "Pali Naka",
    "Pant Nagar",
    "Parekh Nagar Kandivali West",
    "Parel",
    "Parel Village",
    "Park Road",
    "Parshiwada",
    "Pathanwadi",
    "Pedder Road",
    "Perry Road",
    "Pirojshanagar",
    "Poonam Nagar Jogeshwari East",
    "Powai",
    "Prabhadevi",
    "Premier Residencies",
    "Raheja Township",
    "Raheja Vihar",
    "Raje Sambhaji Nagar",
    "Rajendra Nagar",
    "Rajiv Gandhi Nagar Bhandup West",
    "Rambaug Powai",
    "Ramgad Nagar Mulund West",
    "Riddhi Gardens",
    "Royal Palms Estate",
    "Saibaba Nagar Borivali West",
    "Saint Thomas Church Road",
    "Saki Naka",
    "Samata Nagar Thakur Village",
    "Sambhaji Nagar Mulund West",
    "Sangharsh Nagar",
    "Santacruz",
    "Santacruz East",
    "Santacruz West",
    "Sayani Road",
    "Sector 1 Charkop",
    "Sector 2 Charkop",
    "Sector 8 Charkop",
    "Sector 9 Charkop",
    "Seven Bungalows",
    "Sewri",
    "Shanti Park",
    "Shantivan",
    "Shastri Nagar Andheri West",
    "Shastri Nagar Mitha Nagar",
    "Shell Colony",
    "Shitladevi Chawl",
    "Shiv Kutir",
    "Shivaji Nagar - Aarey Milk Colony",
    "Shivaji Park",
    "Siddharth Nagar Goregaon West",
    "Sindhi Colony Sion",
    "Sion",
    "Sion Chunabhatti",
    "Sion Hospital Colony",
    "Subhash Nagar Bhandup West",
    "Subhash Road",
    "Sunder Nagar Malad West",
    "Swastik Park",
    "Tagore Nagar",
    "Tardeo",
    "Tarun Bharat Society",
    "Teachers Colony",
    "Teen Batti",
    "Thakur Complex",
    "Thakur Village",
    "Tilak Nagar Chembur",
    "Tilak Nagar Goregaon West",
    "Tilak Nagar Sewri",
    "Tivri",
    "Ulhasnagar",
    "Union Park",
    "Unnat Nagar Goregaon West",
    "Upper Worli",
    "Utkarsh Nagar",
    "Vardhman Nagar",
    "Vasai",
    "Vasai East",
    "Vasai West",
    "Vazira Naka Borivali West",
    "Veera Desai Industrial Estate",
    "Versova",
    "Vikhroli East",
    "Vikhroli Village",
    "Vikhroli West",
    "Vile Parle",
    "Vile Parle East",
    "Vile Parle West",
    "Virar",
    "Virar East",
    "Virar West",
    "Wadala",
    "Wadala East",
    "Wadala West",
    "Waliv Phata",
    "Walkeshwar",
    "Western Express Highway",
    "Worli",
    "Worli Hill Road",
    "Worli Naka",
    "Worli Sea Face",
    "Yamuna Nagar Andheri West",
    "Yari Road",
    "Yogi Nagar",
  ],
  "New Delhi": [
    "Aali Village",
    "Abul Fazal Enclave Part 1",
    "Acharya Niketan",
    "Adarsh Nagar",
    "Adarsh Nagar Bindapur Extension",
    "Adchini",
    "Adhyapak Nagar",
    "Alaknanda",
    "Aliganj",
    "Amar Colony",
    "Ambedkar Colony Ambedkar Nagar",
    "Amrit Nagar",
    "Anand Gram",
    "Anand Niketan",
    "Anand Parbat",
    "Anand Vihar",
    "Anand Vihar Nangli Sakrawati",
    "Ansari Nagar West",
    "Arjan Garh",
    "Arjun Park",
    "Ashok Nagar",
    "Ashok Niketan",
    "Ashok Vihar",
    "Ashok Vihar Phase 1",
    "Ashok Vihar Phase 2",
    "Ashok Vihar Phase 3",
    "Ashram",
    "Asola",
    "Aya Nagar",
    "Aya Nagar Phase 1",
    "Azad Market",
    "Azadpur",
    "Baba Colony",
    "Badarpur",
    "Badarpur Extension",
    "Badli",
    "Baljit Nagar",
    "Banarsi Das Estate",
    "Baprola",
    "Basai Darapur",
    "Bawana",
    "Beadon Pura",
    "Ber Sarai",
    "Bhagat Vihar",
    "Bhagwan Das Nagar",
    "Bhagwati Garden Extension",
    "Bhajanpura",
    "Bhalswa",
    "Bharat Nagar New Friends Colony",
    "Bharat Vihar",
    "Bhola Nath Nagar",
    "Bijwasan",
    "Bindapur",
    "Bk Dutt Colony",
    "Block 3 Ramesh Nagar",
    "Block 32 East Patel Nagar",
    "Block 4 Subhash Nagar",
    "Block A Mohan Garden",
    "Block B Rajouri Garden",
    "Block B Sewak Park",
    "Block B Surajmal Vihar",
    "Block B West Patel Nagar",
    "Block B4 Safdarjung Enclave",
    "Block BH Shalimar Bagh",
    "Block BJ Shalimar Bagh",
    "Block BP Shalimar Bagh",
    "Block C Bhajanpura",
    "Block C Dashrath Puri",
    "Block F Karam Pura",
    "Block F Palam Extension",
    "Block ND Dakshini Pitampura",
    "Block R Mohan Garden Razapur Khurd",
    "Block T West Patel Nagar",
    "Block W 22 South Sainik Farm",
    "Block WZ Uttam Nagar",
    "Budh Vihar",
    "Budh Vihar Phase 2",
    "Burari",
    "C2 Block Janakpuri",
    "Chanakya Place",
    "Chandan Hola",
    "Chander Vihar",
    "Chandra Nagar",
    "Chawri Bazar",
    "Chhatarpur Extension",
    "Chhattarpur",
    "Chhattarpur Enclave Phase 1",
    "Chhattarpur Enclave Phase 2",
    "Chhawla",
    "Chirag Delhi",
    "Chittaranjan Park",
    "Chittaranjan Park Block A",
    "Chittaranjan Park Block C",
    "Chokhandi",
    "Co operative Group Housing Societies Pitampura",
    "Commonwealth Games Village",
    "Connaught Place",
    "D Block Saket",
    "Dabri",
    "Dabri Extension",
    "Dakshini Pitampura",
    "Dakshinpuri",
    "Daryaganj",
    "Dasghara",
    "Dashrath Puri",
    "Daya Basti",
    "Dayanand Colony",
    "DDA",
    "Defence Colony",
    "Dera Mandi",
    "Devli",
    "Dhaka Village",
    "Dhirpur Village",
    "Dilshad Garden",
    "DLF Farms",
    "Durga Vihar",
    "Dwarka",
    "Dwarka Mor",
    "Dwarka Sector 19B",
    "East Of Kailash",
    "East of Kailash Block B",
    "East of Kailash Block F",
    "Freedom Fighter Colony",
    "Freedom Fighters Enclave",
    "Friends Colony",
    "Friends Colony West",
    "Gandhi Vihar",
    "Ganesh Nagar",
    "Ganga Vihar",
    "Garhi",
    "Gautam Nagar",
    "Geeta Colony",
    "Geetanjali Enclave",
    "Ghazipur",
    "Ghitorni",
    "Giri Nagar",
    "GK I",
    "GK II",
    "Gokalpur East",
    "Golf Course Road",
    "Golf Links",
    "Gopal Nagar Extension",
    "Govindpuri",
    "Goyla Dairy",
    "Goyla Village",
    "Greater Kailash",
    "Greater Kailash 2 E Block",
    "Greater Kailash 4 NRI Colony",
    "Greater Kailash Enclave 1",
    "Greater Kailash Enclave 2",
    "Green Park",
    "Green Park Extension",
    "GTB Enclave",
    "GTB Nagar",
    "Gujarat Vihar",
    "Gujranwala Town",
    "Gulmohar Park",
    "Guru Arjun Nagar",
    "Guru Harikishan Nagar",
    "Haiderpur",
    "Haji Colony",
    "Hardev Nagar",
    "Hari Enclave",
    "Hari Nagar",
    "Harsh Vihar Pitampura",
    "Hastsal",
    "Hauz Khas",
    "Hauz Khas Enclave",
    "Hauz Rani",
    "Hemkunt Colony",
    "IGNOU Main Road",
    "Inderpuri",
    "Indira Vihar",
    "Indra Enclave",
    "Indra Park Extension",
    "Indraprastha",
    "IP Extension",
    "J Block Saket",
    "Jagat Puri Krishna Nagar",
    "Jagatpuri",
    "Jagriti Enclave",
    "Jahangirpuri",
    "Jaitpur Extension Part 2",
    "Janak Park",
    "Janakpuri",
    "Janakpuri Block A2",
    "Janakpuri Block B1",
    "Janakpuri Block C2A",
    "Jangpura",
    "Jangpura A",
    "Jangpura Extension",
    "Jasola",
    "Jasola Vihar",
    "Jaunapur",
    "Jawahar Nagar",
    "Jeevan Niketan",
    "Jhandewalan",
    "Jharoda Majra",
    "Jhilmil Colony",
    "Jivan Park Rani Bagh",
    "Johripur",
    "Jonapur",
    "Jorbagh Tri Nagar",
    "Jyoti Nagar East",
    "Kabir Nagar Vijay Park",
    "Kabool Nagar",
    "Kailash Colony",
    "Kailashpuri",
    "Kakrola",
    "Kalkaji",
    "Kalu Sarai",
    "Kalyan Vihar",
    "Kamla Nagar",
    "Kapashera",
    "Kapashera Samalkha Road",
    "Karala",
    "Karawal Nagar",
    "Karol Bagh",
    "Keshav Puram",
    "Khajuri Khas",
    "Khanpur",
    "Khichripur",
    "Khirki Extension",
    "Kiran Garden",
    "Kiran Vihar",
    "Kirari Suleman Nagar",
    "Kirti Nagar",
    "Kishan Ganj",
    "Kishangarh",
    "Kishangarh Village",
    "Kohat Enclave",
    "Kondli",
    "Kotla Mubarakpur",
    "Krishna Nagar",
    "Krishna Nagar Karol Bagh",
    "Krishna Nagar-Safdarjung Enclave",
    "Kucha Pati Ram",
    "Kundan Nagar",
    "Lado Sarai",
    "Lajpat Nagar",
    "Lajpat Nagar 1",
    "Lajpat Nagar 2",
    "Lajpat Nagar 3",
    "Lajpat Nagar 4",
    "Lajwanti Garden",
    "Laxmi Bai Nagar",
    "Laxmi Nagar",
    "Laxmi Vihar",
    "Laxmi Vihar Nawada",
    "Lok Nayak Puram",
    "Lok Vihar",
    "Madan Park",
    "Madanpur Khadar Village",
    "Madhu Vihar",
    "Madhu Vihar Patparganj",
    "Maharani Bagh",
    "Mahaveer Nagar",
    "Mahavir Enclave",
    "Mahavir Enclave Part 1",
    "Mahavir Enclave Part 2",
    "Mahendra Park",
    "Mahendru Enclave",
    "Mahindra Park",
    "Mahipalpur",
    "Mahipalpur Village",
    "Maidan Garhi",
    "Malka Ganj",
    "Mall Road",
    "Malviya Nagar",
    "Mandakini Enclave",
    "Mandawali",
    "Mangolpur Kalan",
    "Mangolpuri",
    "Manohar Park",
    "Mansa Ram Park",
    "Mansarovar garden",
    "Masjid Moth",
    "Masoodpur",
    "Matiala",
    "Mayur Kunj",
    "Mayur Vihar",
    "Mayur Vihar 1",
    "Mayur Vihar Phase 1 Extension",
    "Mayur Vihar Phase 2",
    "Mayur Vihar Phase 3",
    "Mehrauli",
    "Mianwali Nagar",
    "Mithapur",
    "Mithapur Extension",
    "Model Town",
    "Model Town Phase 3",
    "Mohammadpur Majri",
    "Mohan Garden",
    "Mohan Garden Uttam Nagar",
    "Mohit Nagar",
    "Molarband",
    "Molarband Extension",
    "Moti Bagh",
    "Moti Nagar",
    "Mukherjee Nagar",
    "Mukherjee Nagar Burari",
    "Mundka",
    "Munirka",
    "Munirka Enclave",
    "Najafgarh",
    "Nangli Vihar",
    "Nangloi",
    "Nangloi Jat",
    "Naraina",
    "Naraina Village",
    "Narela",
    "Nathu Colony",
    "Nawada",
    "Neb Sarai",
    "Neb Sarai Saket",
    "Nehru Enclave",
    "Nehru Nagar",
    "Nehru Vihar",
    "New Ashok Nagar",
    "New Friends Colony",
    "New Kondli",
    "New Mahavir Nagar",
    "New Modern Shahdara",
    "New Moti Nagar",
    "New Multan Nagar",
    "New Patel Nagar",
    "New Rajendra Nagar",
    "New Ranjeet Nagar",
    "New Rohtak Road",
    "Nilothi",
    "Nilothi Village",
    "Nirankari Colony",
    "Nirman Vihar",
    "Nizamuddin East",
    "Nizamuddin West",
    "Old Govindpura",
    "Old Gupta Colony",
    "Old Mahavir Nagar",
    "Old Nangal",
    "Old Palam Road",
    "Old Rajendra Nagar",
    "Old Shahabad Muhammad Pur",
    "Outram Lines",
    "Padam Nagar",
    "Palam",
    "Palam Colony",
    "Palam Extension",
    "Pamposh Enclave",
    "Panchsheel Enclave",
    "Panchsheel Park",
    "Panchshil Enclave",
    "Pandav Nagar",
    "Pankha Road",
    "Paryavaran Complex",
    "Paschim Puri",
    "Paschim Vihar",
    "Paschim Vihar Block A3",
    "Paschim Vihar Block B2",
    "Patel Garden",
    "Patel Nagar",
    "Patel Nagar East",
    "Patel Nagar South",
    "Patel Nagar West",
    "Patparganj",
    "Phase 5 Aya Nagar",
    "Pitampura",
    "Pochanpur Colony",
    "Pocket 10 Sector B Vasant Kunj",
    "Pocket 5 Sector 22 Rohini",
    "Poorvi Pitampura",
    "Prahlad Pur Banger",
    "Prashant Vihar",
    "Preet Vihar",
    "Prem Nagar 3",
    "Prem Nagar Janakpuri",
    "Prem Nagar Najafgarh",
    "Pul Prahlad Pur",
    "Punjabi Bagh",
    "Punjabi Bagh East",
    "Punjabi Bagh West",
    "Pushpanjali Enclave",
    "Qutub Vihar",
    "Qutub Vihar Phase 1",
    "Qutub Vihar Phase 2",
    "Raghu Nagar",
    "Raj Nagar 2",
    "Rajdhani Park",
    "Rajendra Nagar",
    "Rajouri Garden",
    "Rajpur Khurd",
    "Rajpur Khurd Extension",
    "Ram Nagar",
    "Rama Park",
    "Ramesh Nagar",
    "Rana Pratap Bagh",
    "Rani Bagh Pitam Pura",
    "Ravi Nagar",
    "Razapur Khurd",
    "Rohini",
    "Rohtak Road",
    "Roop Nagar",
    "Roshanpura",
    "Sadh Nagar",
    "Sadhna Enclave",
    "Safdarjung Development Area",
    "Safdarjung Enclave",
    "Sagarpur",
    "Sagarpur West",
    "Sai Baba Mandir Road",
    "Saini Enclave",
    "Sainik Farm",
    "Sainik Nagar",
    "Saket",
    "Samalkha",
    "Samaspur Village",
    "Sandesh Vihar",
    "Sangam Vihar",
    "Sangam Vihar Wazirabad",
    "Sanjay Colony Narela",
    "Sant Nagar East of Kailash",
    "Sarai Rohilla",
    "Sarita Vihar",
    "Sarita Vihar Pocket H",
    "Sarita Vihar Pocket L",
    "Sarvapriya Vihar",
    "Sat Bari",
    "Satya Niketan",
    "Savitri Nagar Village",
    "Sector 1 Dwarka",
    "Sector 1 Rohini",
    "Sector 10 Dwarka",
    "Sector 11 Dwarka",
    "Sector 11 Rohini",
    "Sector 12 Dwarka",
    "Sector 13 Dwarka",
    "Sector 13 Rohini",
    "Sector 14 Dwarka",
    "Sector 14 Rohini",
    "Sector 15 Dwarka",
    "Sector 15 Rohini",
    "Sector 16 Rohini",
    "Sector 16B Dwarka",
    "Sector 17 Dwarka",
    "Sector 17 Rohini",
    "Sector 18 Dwarka",
    "Sector 18 Rohini",
    "Sector 19 Dwarka",
    "Sector 19 Rohini",
    "Sector 2 Dwarka",
    "Sector 2 Rohini",
    "Sector 20 Rohini",
    "Sector 21 Rohini",
    "Sector 22 Dwarka",
    "Sector 22 Rohini",
    "Sector 23 Dwarka",
    "Sector 23 Rohini",
    "Sector 23B Dwarka",
    "Sector 24 Rohini",
    "Sector 25 Dwarka",
    "Sector 25 Rohini",
    "Sector 26 Dwarka",
    "Sector 28 Dwarka",
    "Sector 28 Rohini",
    "Sector 3 Dwarka",
    "Sector 3 Rohini",
    "Sector 34 Rohini",
    "Sector 35 Rohini",
    "Sector 4 Dwarka",
    "Sector 4 Rohini",
    "Sector 5 Dwarka",
    "Sector 5 Rohini",
    "Sector 6 Dwarka",
    "Sector 6 Pocket 2 Dwarka",
    "Sector 6 Rohini",
    "Sector 7 Dwarka",
    "Sector 7 Rohini",
    "Sector 8 Dwarka",
    "Sector 8 Rohini",
    "Sector 9 Dwarka",
    "Sector 9 Rohini",
    "Sector A6 Narela",
    "Sector B Vasant Kunj",
    "Sector C Vasant Kunj",
    "Sector D Vasant Kunj",
    "Seelampur",
    "Shadipur",
    "Shahbad Daulatpur Village",
    "Shahdara",
    "Shahpur Jat",
    "Shakarpur",
    "Shakarpur Khas",
    "Shakti Nagar",
    "Shalimar bagh",
    "Shalimar Bagh AG Block",
    "Shalimar Bagh AH Block",
    "Shalimar Bagh Poorvi",
    "Shanti Kunj",
    "Shanti Niketan",
    "Shanti Vihar",
    "Shastri Nagar",
    "Shastri Park",
    "Sheikh Sarai",
    "Sheikh Sarai Phase 1",
    "Sheikh Sarai Phase 2",
    "Shiv Nagar",
    "Shiv Nagar Extension",
    "Shiv Park Kakrola",
    "Shiv Vihar",
    "Shivaji Nagar",
    "Shivaji Park",
    "Shivalik Road",
    "Shreshtha Vihar",
    "Shubham Enclave",
    "Shyam Enclave",
    "Shyam Nagar",
    "Shyam Nagar Okhla",
    "Shyam Vihar 2",
    "Shyam Vihar Phase 1",
    "Siddhartha Enclave",
    "Sitapuri",
    "Sitapuri Extension 2",
    "Soami Nagar South",
    "South Extension",
    "South Extension 1",
    "South Extension 2",
    "Sri Niwaspuri",
    "St Nagar Burari",
    "Subhash Nagar",
    "Sukhdev Vihar",
    "Sultanpur",
    "Sunder Nagar",
    "Surajmal Vihar",
    "Surya Enclave",
    "Swasthya Vihar",
    "Tagore Garden",
    "Tagore Garden Extension",
    "Tigri",
    "Tihar Village",
    "Tilak Nagar",
    "Transit Camp",
    "Tri Nagar",
    "Trilokpuri",
    "Tughlakabad Extension",
    "Tyagi Colony Nangloi Extension",
    "Uday Park",
    "Uttam Nagar",
    "Uttam Nagar East",
    "Uttam Nagar Nawada",
    "Uttam Nagar West",
    "Uttari Pitampura",
    "Vasant Kunj",
    "Vasant Kunj Enclave",
    "Vasant Vihar",
    "Vasundhara Enclave",
    "Vigyan Vihar",
    "Vijay Colony Vijay Nagar",
    "Vijay Nagar",
    "Vijay Vihar",
    "Vikas Puri Extension Part 1",
    "Vikaspuri",
    "Vikaspuri Block D",
    "Vikaspuri Block F",
    "Vikaspuri Block H",
    "Vikaspuri Block J",
    "Vinoba Puri",
    "Vipin Garden",
    "Vipin Garden Extension North Block",
    "Virender Nagar",
    "Vishnu Garden",
    "Vishwakarma Colony",
    "Vishwas Nagar",
    "Vishwas Park",
    "Vivek Vihar",
    "Vivek Vihar Phase 1",
    "Wazir Nagar",
    "Wazirabad",
    "Yadav Park Extension",
    "Yamuna Vihar",
    "Yojna Vihar",
  ],
} as const

export type SupportedCity = keyof typeof LOCALITIES_BY_CITY
